name: Fetch today's new papers

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.18
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Fetch latest data
      run: python scrape_daily.py
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A ./data_scraped
        timestamp=$(date -u)
        git commit -m "Add the latest data: ${timestamp}" || exit 0
        git push
